// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8_mCIrDiaQZ-nvR6e52KiItL9yrvllTg',
    appId: '1:914098663282:web:1c9fcef013fd7f48c337eb',
    messagingSenderId: '914098663282',
    projectId: 'coinone-817e0',
    authDomain: 'coinone-817e0.firebaseapp.com',
    storageBucket: 'coinone-817e0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMZbZwCUT-k-tJZ3fio9AQSJUjR4imUKQ',
    appId: '1:914098663282:android:01e6f70b75b2715ec337eb',
    messagingSenderId: '914098663282',
    projectId: 'coinone-817e0',
    storageBucket: 'coinone-817e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC60P5adru2hBZ5Txo_bFvoPa561PpuWMQ',
    appId: '1:914098663282:ios:c829ed6a2c35f19ec337eb',
    messagingSenderId: '914098663282',
    projectId: 'coinone-817e0',
    storageBucket: 'coinone-817e0.appspot.com',
    iosBundleId: 'com.example.coinone',
  );
}
